name: build the release binaries
description: build the release binaries
inputs:
  release_name:
    description: "The name of the release"
    required: true
  github_token:
    description: "The github token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create release output directory
      shell: bash
      run: mkdir -p releases/client releases/node
    #---------------------------------------------------------------------------
    # Anoma Client binary
    - name: build the anoma client release
      shell: bash
      run: |
        MIX_ENV=prod mix do --app anoma_client escript.build
        mv apps/anoma_client/anoma_client releases/client/anoma_client
    #---------------------------------------------------------------------------
    # Anoma Node binary
    - name: build the anoma node release
      shell: bash
      run: |
        MIX_ENV=prod mix do --app anoma_client escript.build
        mv apps/anoma_client/anoma_client releases/client/anoma_node
    #---------------------------------------------------------------------------
    # Publish releases
    - name: publish client release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        gh release upload releases/client/anoma_node
