---
environment: {CARGO_HOME: /usr/local/rust/project/.cargo, CARGO_INCREMENTAL: '0',
  GIT_LFS_SKIP_SMUDGE: '1'}
kind: pipeline
name: anoma-ci-build-pr
node: {project: anoma}
steps:
- commands: [echo "hello world"]
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  name: test
  pull: if-not-exists
trigger:
  event: [pull_request]
type: docker
workspace: {path: /usr/local/rust/project}
---
kind: signature
hmac: 9d01f86c5ffa6d623f0094fbb15b5c2d1d47fe6ed5863ad08c231a853c8c7987

...
