---
clone: {disable: true}
environment: {CARGO_HOME: /usr/local/rust/project/.cargo, CARGO_INCREMENTAL: '0',
  GIT_LFS_SKIP_SMUDGE: '1'}
kind: pipeline
name: anoma-ci-build-pr
node: {project: anoma}
steps:
- commands: [git clone $DRONE_GIT_HTTP_URL ., git fetch --all, git checkout $DRONE_COMMIT]
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  name: clone
  pull: never
trigger:
  event: [pull_request]
type: docker
workspace: {path: /usr/local/rust/project}
---
kind: signature
hmac: 81a833b3fc23bd541b4700f694158bbc55ea1bf651cf6b8046ab943414d5b737

...
