---
clone: {disable: true}
environment: {CARGO_HOME: /usr/local/rust/project/.cargo, CARGO_INCREMENTAL: '0',
  GIT_LFS_SKIP_SMUDGE: '1'}
kind: pipeline
name: anoma-ci-misc-pr
node: {project: anoma}
steps:
- commands: [git clone $DRONE_GIT_HTTP_URL ., git fetch --all, git checkout $DRONE_TARGET_BRANCH,
    git merge $DRONE_COMMIT, CONFLICTS=$(git ls-files -u | wc -l), 'if [ "$CONFLICTS"
      -gt 0 ]; then exit 1; fi;exit 0']
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  name: clone
  pull: never
trigger:
  event: [pull_request]
type: docker
workspace: {path: /usr/local/rust/wasm}
---
kind: signature
hmac: f0325fa2fee3de4eb0a663c71d43a08529a667bcc3b757941603067f32ea7f3f

...
