---
environment: {CARGO_HOME: /usr/local/rust/project/.cargo, CARGO_INCREMENTAL: '0',
  GIT_LFS_SKIP_SMUDGE: '1'}
kind: pipeline
name: anoma-ci-build-pr
node: {project: anoma}
steps:
- commands: [echo "hello world"]
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
  name: test
  pull: if-not-exists
trigger:
  event: [pull_request]
type: docker
workspace: {path: /usr/local/rust/project}
---
kind: signature
hmac: ebfec4c7c33b4147a67e993af2a248c9d6f951a2ca2aec4c80e6eb495438422a

...
