name: lint elixir code base
description: lint elixir code base
runs:
  using: "composite"
  steps:
    # checkout the repo
    - name: Check out the repository to the runner
      uses: actions/checkout@v4

    # install os deps
    - uses: ./.github/workflows/os_dependencies

    # install erlang/elixir/protobuf
    - uses: ./.github/workflows/elixir_setup

    # setup build cache
    - uses: ./.github/workflows/cache
      with:
        os: ${{ runner.os }}
        mix_env: ${{ matrix.mix_env }}
        paths: |
          ${{ github.workspace }}/deps
          ${{ github.workspace }}/_build

    # run mix credo
    # - run: MIX_ENV=${{matrix.mix_env}} mix credo

    # check formatting
    # - run: MIX_ENV=${{matrix.mix_env}} mix format --check-formatted

    # dialyzer
    # - run: MIX_ENV=${{matrix.mix_env}} mix dialyzer --format github

    # whitespace check
    # - run: git diff-tree --check 4b825dc642cb6eb9a060e54bf8d69288fbee4904 HEAD
