[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "anoma_vm_env"
resolver = "2"
version = "0.4.0"

[features]
default = ["ABCI"]

ABCI = [
  "anoma/ABCI",
]

ABCI-plus-plus = [
  "anoma/ABCI-plus-plus",
]

[dependencies]
anoma = {path = "../shared", default-features = false}
anoma_macros = {path = "../macros"}
borsh = "0.9.0"
jubjub = { version = "0.8"}
bls12_381 = { version = "0.6"}
#libmasp = { git = "https://github.com/murisi/masp", branch = "murisi/masp-addons" }
masp_primitives = { git = "https://github.com/murisi/masp", branch = "murisi/masp-addons" }
masp_proofs = { git = "https://github.com/murisi/masp", branch = "murisi/masp-addons" }
zcash_primitives = { git = "https://github.com/murisi/masp", branch = "murisi/masp-addons" }
zcash_proofs = { git = "https://github.com/murisi/masp", branch = "murisi/masp-addons" }
bellman = { version = "0.11.1", features = ["groth16"] }
ff = { version = "0.11" }
