name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  wasm:
    runs-on: ${{ matrix.os }}
    # container:
    #   image: ghcr.io/fraccaman/anoma:wasm-0.6.1
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        nightly_version: [nightly-2022-05-20]
        wasm_cache_version: ["v1"]
        anoma_cache_version: ["v1"]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # - name: Setup rust toolchain
      #   uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
      #   with:
      #     target: wasm32-unknown-unknown
      #     profile: default
      #     override: true
      # - name: Setup rust nightly
      #   uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
      #   with:
      #     toolchain: ${{ matrix.nightly_version }}
      #     target: wasm32-unknown-unknown
      #     profile: default
      - name: Show rust toolchain info
        run: rustup show
      - name: Cache cargo
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ./target
            ./wasm/tx_template/target
            ./wasm/vp_template/target
            ./wasm_for_tests/wasm_source/target
          key: ${{ runner.os }}-wasm-${{ matrix.wasm_cache_version }}-cargo-${{ hashFiles('**/wasm/wasm_source/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-wasm-${{ matrix.wasm_cache_version }}-cargo-
      - name: Build WASM
        run: cp wasm/checksums.json wasm/original-checksums.json && make build-wasm-scripts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: |
            wasm/tx_*.wasm
            wasm/vp_*.wasm
            wasm/checksums.json
      - name: Test Wasm
        run: make test-wasm
      - name: Check wasm up-to-date
        run: cmp -- wasm/checksums.json wasm/original-checksums.json
      - name: Clean cache folder
        continue-on-error: true
        run: cargo install cargo-cache --no-default-features --features ci-autoclean cargo-cache && cargo-cache