name: Build docker images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The docker image tag'     
        required: true 

jobs:
  docs:
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        make:
          - name: Build & Push WASM docker image
            image: wasm
            path: ./docker/anoma-wasm
          - name: Build and Push Anoma docker image
            image: anoma
            path: ./docker/anoma-build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/fraccaman/anoma
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ${{ matrix.make.name }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.make.path }}/
          file: ${{ matrix.make.path }}/Dockerfile
          push: true
          tags: ${{ github.event.inputs.tag  }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ matrix.make.image }}-${{ github.event.inputs.tag  }}
          cache-to: type=inline