name: Pull Request

on:
  pull_request:
    branches: [ "base" ]

permissions:
  contents: read

jobs:
  build:
    name: Tests and dialyzer
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v4.1.0
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.16.0
      with:
        elixir-version: '1.15.6'
        otp-version: '26.1.2'
    - name: Restore dependencies cache
      uses: actions/cache@v3.3.2
      with:
        path: deps
        key: |
          mix-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          mix-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-
    - name: Install dependencies
      run: mix deps.get
    - name: Restore PLT cache
      id: plt_cache
      uses: actions/cache/restore@v3.3.2
      with:
        path: plts
        key: |
          plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-
    - name: Create PLTs
      if: steps.plt_cache.outputs.cache-hit != 'true'
      run: mix dialyzer --plt
    - name: Save PLT cache
      uses: actions/cache/save@v3.3.2
      if: steps.plt_cache.outputs.cache-hit != 'true'
      with:
        path: plts
        key: |
          plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
    - name: Run tests
      run: mix test
    - name: Run dialyzer
      run: mix dialyzer --format github
